#!/usr/bin/env python3
"""
508 Media Co. client video-results tracker → Squarespace + Artifact.

  page.html                                  source (edit this)
  squarespace-page-header-injection.html     paste into Page Settings → Advanced → Page Header Code Injection
  index.html                                 Artifact / local preview

Same pattern as hq-southpark / hds-fleet: the site-wide 508 footer injection draws the homepage (#mc508)
on every page, so the injection hides it and mounts #trk508 from a <template> once the DOM is ready.
Entries live in the visitor's localStorage on www.508mediaco.com; nothing is sent anywhere.
"""
import pathlib

HERE = pathlib.Path(__file__).parent
src = (HERE / "page.html").read_text()
head = src[src.index('<link rel="preconnect"'):src.index("</style>") + len("</style>")]
body = src[src.index('<div id="trk508">'):src.index("<script>")].strip()
script = src[src.index("<script>") + len("<script>"):src.index("</script>")].strip()

injection = f"""<!-- 508 Media Co. | client video results tracker. Generated by client-insights-tracker/build.py; edit page.html. -->
<meta name="robots" content="noindex,nofollow">
{head}
<style>#mc508{{display:none!important}} html,body{{background:#06070A!important}}</style>
<template id="trk508tpl">
{body}
</template>
<script>
document.addEventListener('DOMContentLoaded', function(){{
  var t = document.getElementById('trk508tpl');
  if (!t || document.getElementById('trk508')) return;
  document.body.appendChild(t.content.cloneNode(true));
  {script}
}});
</script>
"""
(HERE / "squarespace-page-header-injection.html").write_text(injection)

(HERE / "index.html").write_text(f"""<title>Video Results Tracker</title>
{head}<style>:root{{color-scheme:dark;background:#06070A}} html,body{{margin:0;background:#06070A}}</style>
{body}
<script>{script}</script>
""")
print("injection", len(injection), "bytes")
