#!/usr/bin/env python3
"""
Hunter Quinn South Park case study → Squarespace.

  page.html                          source (edit this)
  squarespace-page-header-injection.html   paste into Page Settings → Advanced → Page Header Code Injection
  preview.html                       local preview with the same assets

The site-wide 508 footer injection draws the homepage (#mc508) on every page, so the
injection hides it and mounts #hq508 from a <template> once the DOM is ready.
"""
import pathlib, re

HERE = pathlib.Path(__file__).parent
CFG = {
    "MEDIA": "https://drewreid508.github.io/508mediaco/hq-southpark",
    "DOWNLOAD_URL": "https://we.tl/t-Fju2e5WGPwsNxqKx",   # WeTransfer, made Oct 6 with 30-day expiry
    "DOWNLOAD_UNTIL": "Nov 5",
    "REVIEW_URL": "https://g.page/r/CQRtijkKqWhOEBI/review",
}

src = (HERE / "page.html").read_text()
for k, v in CFG.items():
    src = src.replace("{{" + k + "}}", v)

head = src[src.index('<link rel="preconnect"'):src.index("</style>") + len("</style>")]
body = src[src.index('<div id="hq508">'):src.index("<script>")].strip()
script = src[src.index("<script>") + len("<script>"):src.index("</script>")].strip()

injection = f"""<!-- 508 Media Co. | Hunter Quinn South Park case study. Generated by hq-southpark/build.py; edit page.html. -->
<meta name="robots" content="noindex,nofollow">
{head}
<style>#mc508{{display:none!important}} html,body{{background:#07080B!important}}</style>
<template id="hq508tpl">
{body}
</template>
<script>
document.addEventListener('DOMContentLoaded', function(){{
  var t = document.getElementById('hq508tpl');
  if (!t || document.getElementById('hq508')) return;
  document.body.appendChild(t.content.cloneNode(true));
  {script}
}});
</script>
"""
(HERE / "squarespace-page-header-injection.html").write_text(injection)

preview = f"""<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>South Park · preview</title>
{head}<style>html,body{{margin:0;background:#07080B}}</style></head><body>
{body}
<script>{script}</script></body></html>
"""
(HERE / "preview.html").write_text(preview.replace(CFG["MEDIA"], "."))
print("injection", len(injection), "bytes")
