#!/usr/bin/env python3
"""
Hannah's Detailing & Supply fleet ads delivery → Squarespace + Artifact.

  page.html                                  source (edit this)
  squarespace-page-header-injection.html     paste into Page Settings → Advanced → Page Header Code Injection
  index.html                                 Artifact / local preview (assets relative, ./media)

Same pattern as hq-southpark: the site-wide 508 footer injection draws the homepage (#mc508) on
every page, so the injection hides it and mounts #hds508 from a <template> once the DOM is ready.
Tokens are {{KEY}} with full names only (a bare MEDIA token once ate the word in "508 MEDIA CO.").
"""
import pathlib

HERE = pathlib.Path(__file__).parent
STAR = ('<svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true">'
        '<path d="M12 2.5l2.9 6.1 6.6.8-4.9 4.6 1.3 6.6L12 17.3 6.1 20.6l1.3-6.6L2.5 9.4l6.6-.8z"/></svg>')
CFG = {
    "MEDIA": "https://drewreid508.github.io/508mediaco/hds-fleet",
    "RAW_URL": "https://we.tl/t-3tanymarhkRG8KkO",   # raw footage WeTransfer, sent Oct 10
    "FINALS_URL": "",     # optional WeTransfer for the 4 full-quality finals; empty removes that card
    "REVIEW_URL": "https://g.page/r/CQRtijkKqWhOEBI/review",
    "STARS": STAR * 5,
    "STAR": STAR,
}

def render(media):
    src = (HERE / "page.html").read_text()
    for k, v in {**CFG, "MEDIA": media}.items():
        src = src.replace("{{" + k + "}}", v)
    assert "{{" not in src, "unfilled token"
    head = src[src.index('<link rel="preconnect"'):src.index("</style>") + len("</style>")]
    body = src[src.index('<div id="hds508">'):src.index("<script>")].strip()
    script = src[src.index("<script>") + len("<script>"):src.index("</script>")].strip()
    return head, body, script

head, body, script = render(CFG["MEDIA"])
injection = f"""<!-- 508 Media Co. | Hannah's Detailing & Supply fleet ads delivery. Generated by hds-fleet/build.py; edit page.html. -->
<meta name="robots" content="noindex,nofollow">
<meta property="og:image" content="{CFG['MEDIA']}/media/ceramic-wide.jpg">
{head}
<style>#mc508{{display:none!important}} html,body{{background:#06070A!important}}</style>
<template id="hds508tpl">
{body}
</template>
<script>
document.addEventListener('DOMContentLoaded', function(){{
  var t = document.getElementById('hds508tpl');
  if (!t || document.getElementById('hds508')) return;
  document.body.appendChild(t.content.cloneNode(true));
  {script}
}});
</script>
"""
(HERE / "squarespace-page-header-injection.html").write_text(injection)

head, body, script = render(".")
(HERE / "index.html").write_text(f"""<title>Hannah's Fleet Delivery</title>
{head}<style>:root{{color-scheme:dark;background:#06070A}} html,body{{margin:0;background:#06070A}}</style>
{body}
<script>{script}</script>
""")
print("injection", len(injection), "bytes")
